/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.OjdbcController;
import dao.JobGradeDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.JobGrade;

/**
 *
 * @author TAMU
 */
public class view extends javax.swing.JFrame {

    private String header[]={"grade level","lowest salary","highest salary"};
    
    public  OjdbcController jgc;
    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        jgc= new OjdbcController();
        jgc.bindingAll(TBLjobgrade, header);
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TBLjobgrade = new javax.swing.JTable();
        PNLdetail = new javax.swing.JPanel();
        txtgradelevel = new javax.swing.JTextField();
        lblgradeleve = new javax.swing.JLabel();
        lbllowestsal = new javax.swing.JLabel();
        txtlowestsal = new javax.swing.JTextField();
        lblhighestsal = new javax.swing.JLabel();
        txthighestsal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        ckboxkategori = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("view");

        TBLjobgrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TBLjobgrade.setToolTipText("okeh tabel");
        TBLjobgrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLjobgradeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLjobgrade);

        PNLdetail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        PNLdetail.setForeground(new java.awt.Color(55, 55, 55));

        txtgradelevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgradelevelActionPerformed(evt);
            }
        });
        txtgradelevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgradelevelKeyPressed(evt);
            }
        });

        lblgradeleve.setText("Grade_ Level");

        lbllowestsal.setText("Lowest_Sal");

        lblhighestsal.setText("Highest_Sal");

        txthighestsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthighestsalActionPerformed(evt);
            }
        });

        jLabel4.setText("Tabel JobGRades");

        btnsimpan.setBackground(new java.awt.Color(90, 40, 240));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(240, 240, 40));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLdetailLayout = new javax.swing.GroupLayout(PNLdetail);
        PNLdetail.setLayout(PNLdetailLayout);
        PNLdetailLayout.setHorizontalGroup(
            PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLdetailLayout.createSequentialGroup()
                .addGroup(PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLdetailLayout.createSequentialGroup()
                        .addComponent(lblhighestsal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthighestsal))
                    .addGroup(PNLdetailLayout.createSequentialGroup()
                        .addComponent(lblgradeleve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgradelevel))
                    .addGroup(PNLdetailLayout.createSequentialGroup()
                        .addComponent(lbllowestsal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlowestsal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnsimpan)
                    .addComponent(btnhapus))
                .addGap(40, 40, 40))
            .addGroup(PNLdetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        PNLdetailLayout.setVerticalGroup(
            PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PNLdetailLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgradelevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgradeleve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllowestsal)
                    .addComponent(txtlowestsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PNLdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthighestsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhighestsal)
                    .addComponent(btnhapus))
                .addGap(5, 5, 5))
        );

        ckboxkategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "grade level", "lowest salary", "highest salary" }));

        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ckboxkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckboxkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PNLdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtgradelevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgradelevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgradelevelActionPerformed

    private void txthighestsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthighestsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthighestsalActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        String kolom = "";
        switch (ckboxkategori.getSelectedIndex()){
            case 0:kolom="grade_level";break;
            case 1:kolom="highest_sal";break;
            case 2:kolom="lowest_sal";break;
            default:
                throw new AssertionError();
        }
       jgc.bindingSearch(TBLjobgrade, header,kolom,txtsearch.getText()); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btncariActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
       boolean hasil = false;
       if (!txtgradelevel.isEnabled()){
           hasil = jgc.update(txtgradelevel.getText(),Integer.parseInt(txtlowestsal.getText()), Integer.parseInt(txthighestsal.getText()));
           jgc.bindingAll(TBLjobgrade, header);
           String pesan = "Gagal update data";
           if(hasil){
           pesan="berhasil update data";
        }
        JOptionPane.showMessageDialog(this, pesan);
        reset();
       }else{
        hasil = jgc.insert(txtgradelevel.getText(),Integer.parseInt(txtlowestsal.getText()),Integer.parseInt(txthighestsal.getText()));
        jgc.bindingAll(TBLjobgrade, header);
        String pesan = "Gagal menambahakan data";
        if(hasil){
            pesan="berhasil menambahkan data";
        }
        JOptionPane.showMessageDialog(this, pesan);
        reset();
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtgradelevelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgradelevelKeyPressed
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgradelevelKeyPressed

    private void TBLjobgradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLjobgradeMouseClicked
        txtgradelevel.setText(TBLjobgrade.getValueAt(TBLjobgrade.getSelectedRow(), 0)+"");
        txtlowestsal.setText(TBLjobgrade.getValueAt(TBLjobgrade.getSelectedRow(), 1)+"");
        txthighestsal.setText(TBLjobgrade.getValueAt(TBLjobgrade.getSelectedRow(), 2)+"");
        txtgradelevel.setEnabled(false);
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_TBLjobgradeMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Apakah ingin dihapus?");
        if (i==0){
        String pesan = "gagal hapus";
        boolean hasil = jgc.delete(txtgradelevel.getText());
        if (hasil) pesan = "berhasil hapus";
            JOptionPane.showMessageDialog(this, pesan);
            jgc.bindingAll(TBLjobgrade, header);
            reset();
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PNLdetail;
    private javax.swing.JTable TBLjobgrade;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> ckboxkategori;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblgradeleve;
    private javax.swing.JLabel lblhighestsal;
    private javax.swing.JLabel lbllowestsal;
    private javax.swing.JTextField txtgradelevel;
    private javax.swing.JTextField txthighestsal;
    private javax.swing.JTextField txtlowestsal;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    public void reset(){
        txtgradelevel.setText("");
        txtlowestsal.setText("");
        txthighestsal.setText("");
        txtsearch.setText("");
        txtgradelevel.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
    }
    
//    public void bindingTabel(){
//        String header[]={"grade level","lowest salary","highest salary"};
//        List<JobGrade> datas = new JobGradeDAO().getAllData();
//        Object[][] data = new Object[datas.size()][3];
//        for (int i = 0; i < datas.size(); i++) {
//            data [i][0] = datas.get(i).getGradelevel();
//            data [i][2] = datas.get(i).getLowestSalary();
//            data [i][1] = datas.get(i).getHighestSalary();
//        }
//        DefaultTableModel model = new DefaultTableModel(data, header);
//        TBLjobgrade.setModel(model);
//    }
}
